### ISSUE TITLE
`polymer-hybrid` branch doesn't seem to exist

### ISSUE THREAD

**Issue by davidmaxwaterman** [LostInBrittany/granite-qrcode-decoder#2]
https://github.com/LostInBrittany/granite-qrcode-scanner/blob/master/README.md

```
The old Polymer 2.x-1.x version is available on the polymer-hybrid branch.
```

What am I missing?

**Comment by davidmaxwaterman** [comment]
Ah, I think the link is wrong - should be:

https://github.com/LostInBrittany/granite-qrcode-scanner/tree/polymer-1.x-hybrid

**Comment by LostInBrittany** [comment]
Oups, I forgot to push one of the branches. 
Right now there are:
- [Polymer 1.x-hybrid](https://github.com/LostInBrittany/granite-qrcode-decoder/tree/polymer-1.x-hybrid)
-  [Polymer 2.x-hybrid](https://github.com/LostInBrittany/granite-qrcode-decoder/tree/polymer-hybrid)
